//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KanColleOpenDB.Properties {
    using System;
    
    
    /// <summary>
    ///   지역화된 문자열 등을 찾기 위한 강력한 형식의 리소스 클래스입니다.
    /// </summary>
    // 이 클래스는 ResGen 또는 Visual Studio와 같은 도구를 통해 StronglyTypedResourceBuilder
    // 클래스에서 자동으로 생성되었습니다.
    // 멤버를 추가하거나 제거하려면 .ResX 파일을 편집한 다음 /str 옵션을 사용하여 ResGen을
    // 다시 실행하거나 VS 프로젝트를 다시 빌드하십시오.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   이 클래스에서 사용하는 캐시된 ResourceManager 인스턴스를 반환합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KanColleOpenDB.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   이 강력한 형식의 리소스 클래스를 사용하여 모든 리소스 조회에 대한 현재 스레드의 CurrentUICulture
        ///   속성을 재정의합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   사용하지 않기과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string FirstPopup_Disable {
            get {
                return ResourceManager.GetString("FirstPopup_Disable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   계속 사용과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string FirstPopup_KeepEnable {
            get {
                return ResourceManager.GetString("FirstPopup_KeepEnable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   OpenDB 통계 전송 플러그인이 설치되었습니다.
        ///서버에 전송하는 옵션은 기본으로 설정되어 있으며, 원하지 않으면 끌 수 있습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string FirstPopup_Text {
            get {
                return ResourceManager.GetString("FirstPopup_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   통계 데이터를 서버로 전송하기과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Option_Enable {
            get {
                return ResourceManager.GetString("Option_Enable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   전송되는 데이터는 다음과 같습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Text_DataInfo {
            get {
                return ResourceManager.GetString("Text_DataInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   장비 개발 데이터, 칸무스 건조 데이터, 칸무스 드롭 데이터과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Text_DatasToSend {
            get {
                return ResourceManager.GetString("Text_DatasToSend", resourceCulture);
            }
        }
    }
}
